import type { AmbulanceRequest, Ambulance, User, Hospital, AmbulanceCrew } from "./types"

export const mockHospitals: Hospital[] = [
  { id: "h1", name: "Mərkəzi Klinika", address: "Bakı, Parlaman pr. 76", isActive: true },
  { id: "h2", name: "Respublika Klinik Xəstəxanası", address: "Bakı, Abbas Mirzə Şərifzadə küç. 196", isActive: true },
  { id: "h3", name: "1 saylı Şəhər Klinik Xəstəxanası (Semaşko)", address: "Bakı, Təbriz küç. 1", isActive: true },
  { id: "h4", name: "Baku Medical Plaza", address: "Bakı, Babək pr. 92N", isActive: true },
  { id: "h5", name: "Liv Bona Dea Hospital", address: "Bakı, Mehdi Abbasov küç. 2", isActive: true },
]

export const mockUsers: User[] = [
  {
    id: "u1",
    firstName: "Fuad",
    lastName: "Əliyev",
    fatherName: "Rasim",
    fin: "1234567",
    role: "Super Admin",
    gender: "Kişi",
    birthDate: "1985-05-15",
    isActive: true,
    phoneNumber: "+994501112233",
  },
  {
    id: "u2",
    firstName: "Aysel",
    lastName: "Qasımova",
    fatherName: "Vaqif",
    fin: "7654321",
    role: "Operator",
    gender: "Qadın",
    birthDate: "1992-10-20",
    isActive: true,
    phoneNumber: "+994504445566",
  },
  {
    id: "u4",
    firstName: "Elnur",
    lastName: "Həsənov",
    fatherName: "Mənsur",
    fin: "B9C8D7E",
    role: "Operator",
    gender: "Kişi",
    birthDate: "1990-08-12",
    isActive: true,
    phoneNumber: "+994503334455",
  },
  {
    id: "u5",
    firstName: "Zəhra",
    lastName: "Məlikova",
    fatherName: "Kamil",
    fin: "F1G2H3J",
    role: "Operator",
    gender: "Qadın",
    birthDate: "1994-12-05",
    isActive: true,
    phoneNumber: "+994502223344",
  },
  {
    id: "u3",
    firstName: "Nicat",
    lastName: "Vəliyev",
    fatherName: "Eldar",
    fin: "A1B2C3D",
    role: "Sürücü",
    gender: "Kişi",
    birthDate: "1988-03-12",
    hospitalId: "h1",
    crewId: "c1",
    isActive: true,
    phoneNumber: "+994551112233",
  },
]

export const mockCrews: AmbulanceCrew[] = [
  {
    id: "c1",
    name: "Briqada #101",
    hospitalId: "h1",
    memberIds: ["u3"],
    isActive: true,
  },
]

export const mockRequests: AmbulanceRequest[] = [
  {
    id: "1",
    dispatcherName: "Əli",
    dispatcherSurname: "Məmmədov",
    dispatcherFatherName: "Həsən",
    fin: "4A5B6C7",
    phoneNumber: "+994501234567",
    callReason: "Ürəktutması",
    callerType: "Başqası üçün",
    location: {
      latitude: 40.4093,
      longitude: 49.8671,
      address: "Nizami küçəsi 10, Bakı",
    },
    ambulanceNumber: "AMB-101",
    status: "Sorğu yekunlaşıb",
    hospitalId: "h1",
    operatorId: "u2",
    driverId: "u3",
    responseTime: 45,
    arrivalTime: 12,
    region: "Nizami",
    createdAt: new Date("2025-01-15T10:30:00"),
    updatedAt: new Date("2025-01-15T10:35:00"),
  },
  {
    id: "2",
    dispatcherName: "Leyla",
    dispatcherSurname: "İbrahimova",
    dispatcherFatherName: "Elxan",
    fin: "3X4Y5Z6",
    phoneNumber: "+994551234568",
    callReason: "Xəsarət",
    callerType: "Özü üçün",
    location: {
      latitude: 40.3777,
      longitude: 49.892,
      address: "28 May küçəsi 45, Bakı",
    },
    status: "Gözləmədədir",
    region: "Nəsimi",
    createdAt: new Date("2025-01-15T11:15:00"),
    updatedAt: new Date("2025-01-15T11:15:00"),
  },
  {
    id: "3",
    dispatcherName: "Ramil",
    dispatcherSurname: "Quliyev",
    dispatcherFatherName: "Təvəkkül",
    fin: "7M8N9P0",
    phoneNumber: "+994701234569",
    callReason: "Yanığ",
    callerType: "Başqası üçün",
    location: {
      latitude: 40.3953,
      longitude: 49.8822,
      address: "Azadlıq prospekti 23, Bakı",
    },
    ambulanceNumber: "AMB-103",
    status: "Ambulans yaxınlaşıb",
    region: "Nərimanov",
    createdAt: new Date("2025-01-15T09:45:00"),
    updatedAt: new Date("2025-01-15T10:00:00"),
  },
  {
    id: "4",
    dispatcherName: "Sənan",
    dispatcherSurname: "Babayev",
    dispatcherFatherName: "Qadir",
    fin: "Q1W2E3R",
    phoneNumber: "+994509876543",
    callReason: "Ürəktutması",
    callerType: "Başqası üçün",
    location: { latitude: 40.4312, longitude: 49.8512, address: "Xətai pr. 12" },
    status: "Sorğu yekunlaşıb",
    hospitalId: "h2",
    operatorId: "u4",
    responseTime: 32,
    region: "Xətai",
    createdAt: new Date("2025-01-15T08:20:00"),
  },
  {
    id: "5",
    dispatcherName: "Aytən",
    dispatcherSurname: "Səfərova",
    dispatcherFatherName: "Murad",
    fin: "T5Y6U7I",
    phoneNumber: "+994514443322",
    callReason: "Xəsarət",
    callerType: "Özü üçün",
    location: { latitude: 40.3621, longitude: 49.8321, address: "Badamdar qəs. 4" },
    status: "Sorğu yekunlaşıb",
    hospitalId: "h3",
    operatorId: "u5",
    responseTime: 55,
    region: "Səbail",
    createdAt: new Date("2025-01-15T12:10:00"),
  },
  {
    id: "6",
    dispatcherName: "Vüqar",
    dispatcherSurname: "Kərimov",
    dispatcherFatherName: "Səlim",
    fin: "O9P8L7K",
    phoneNumber: "+994556667788",
    callReason: "Zəhərlənmə",
    callerType: "Başqası üçün",
    location: { latitude: 40.4521, longitude: 49.9212, address: "Bakıxanov qəs." },
    status: "Sorğu ləğv edilib",
    operatorId: "u2",
    region: "Sabunçu",
    createdAt: new Date("2025-01-15T14:40:00"),
  },
  {
    id: "7",
    dispatcherName: "Nigar",
    dispatcherSurname: "Əhmədova",
    dispatcherFatherName: "Tofiq",
    fin: "M1N2B3V",
    phoneNumber: "+994505556677",
    callReason: "Xəsarət",
    callerType: "Başqası üçün",
    location: { latitude: 40.3812, longitude: 49.8112, address: "Yasamal, İnşaatçılar pr." },
    status: "Ambulans təyin edilib",
    ambulanceNumber: "AMB-104",
    hospitalId: "h4",
    operatorId: "u4",
    region: "Yasamal",
    createdAt: new Date("2025-01-15T15:20:00"),
  },
  {
    id: "8",
    dispatcherName: "Emin",
    dispatcherSurname: "Rzayev",
    dispatcherFatherName: "Cavid",
    fin: "Z9X8C7V",
    phoneNumber: "+994703332211",
    callReason: "Ürəktutması",
    callerType: "Özü üçün",
    location: { latitude: 40.4123, longitude: 49.8712, address: "Nəsimi bazarı yaxınlığı" },
    status: "Gözləmədədir",
    region: "Nəsimi",
    createdAt: new Date("2025-01-15T16:10:00"),
  },
]

export const mockAmbulances: Ambulance[] = [
  {
    id: "1",
    number: "AMB-101",
    isAvailable: false,
    currentLocation: { latitude: 40.4093, longitude: 49.8671, address: "Nizami küçəsi" },
  },
  {
    id: "2",
    number: "AMB-102",
    isAvailable: true,
    currentLocation: { latitude: 40.3777, longitude: 49.892, address: "Yasamal rayonu" },
  },
  {
    id: "3",
    number: "AMB-103",
    isAvailable: false,
    currentLocation: { latitude: 40.3953, longitude: 49.8822, address: "Azadlıq prospekti" },
  },
  {
    id: "4",
    number: "AMB-104",
    isAvailable: true,
    currentLocation: { latitude: 40.405, longitude: 49.8678, address: "Səbail rayonu" },
  },
  {
    id: "5",
    number: "AMB-105",
    isAvailable: true,
  },
]
